services:
    movieV3_db:
        container_name: movieV3_db
        image: postgres:14.3-alpine
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: root
            POSTGRES_DB: movieV3_db
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - '5443:5432'
volumes:
    db-data:
